In [20]:
import pandas as pd

states = pd.read_csv("states.csv")
states

states = states["first_target_year"]
states["nearest_year"] = 2017
states

,Unnamed: 0,Unnamed: 1,Voluntary?,Repealed?,year_enacted,first_target_pct,first_target_abs (MW),first_target_year,second_target_pct,second_target_year,sectors,cost_cap,nearest_year
0,Alabama,AL,False,False,2006.0,0.150,NaN,2025.0,NaN,NaN,NaN,None,2017
1,Alaska,AK,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
2,Arizona,AZ,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
3,Arkansas,AR,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
4,California,CA,False,False,2002.0,0.440,NaN,2024.0,0.52,2027.0,NaN,Fuzzy,2017
5,Colorado,CO,False,False,2004.0,0.300,NaN,2020.0,NaN,NaN,NaN,0.02,2017
6,Connecticut,CT,False,False,1998.0,0.440,NaN,2030.0,NaN,NaN,`,0.058,2017
7,Delaware,DE,False,False,2005.0,0.250,NaN,2025.0,NaN,NaN,NaN,0.03,2017
8,Florida,FL,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
9,Georgia,GA,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
10,Hawaii,HI,False,False,2001.0,0.300,NaN,2020.0,0.40,2030.0,NaN,None,2017
11,Idaho,ID,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
12,Illinois,IL,False,False,2007.0,0.250,NaN,2025.0,NaN,NaN,NaN,0.013,2017
13,Indiana,IN,True,False,2011.0,0.100,NaN,2025.0,NaN,NaN,NaN,None,2017
14,Iowa,IA,False,False,1983.0,NaN,105.0,NaN,NaN,NaN,NaN,None,2017
15,Kansas,KS,False,False,2009.0,0.150,NaN,2019.0,NaN,NaN,NaN,None,2017
16,Kentucky,KY,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
17,Louisiana,LA,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
18,Maine,ME,False,False,1999.0,0.400,NaN,2017.0,NaN,NaN,NaN,0.054,2017
19,Maryland,MD,False,False,2004.0,0.250,NaN,2020.0,NaN,NaN,NaN,0.076,2017
20,Massachusetts,MA,False,False,1997.0,0.350,NaN,2030.0,NaN,NaN,NaN,0.192,2017
21,Michigan,MI,False,False,2008.0,0.150,NaN,2021.0,0.35,2025.0,NaN,0.025,2017
22,Minnesota,MN,False,False,2007.0,0.265,NaN,2025.0,NaN,NaN,NaN,None,2017
23,Mississippi,MS,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
24,Missouri,MO,False,False,2007.0,0.150,NaN,2021.0,NaN,NaN,NaN,0.01,2017
25,Montana,MT,False,False,2005.0,0.150,NaN,2015.0,NaN,NaN,NaN,0.001,2017
26,Nebraska,NE,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
27,Nevada,NV,False,False,1997.0,0.250,NaN,2025.0,NaN,NaN,NaN,None,2017
28,New Hampshire,NH,False,False,2007.0,0.252,NaN,2025.0,NaN,NaN,NaN,0.066,2017
29,New Jersey,NJ,False,False,1991.0,0.500,NaN,2030.0,NaN,NaN,NaN,0.099,2017
30,New Mexico,NM,False,False,2002.0,0.200,NaN,2020.0,NaN,NaN,NaN,0.035,2017
31,New York,NY,False,False,2004.0,0.500,NaN,2030.0,NaN,NaN,NaN,None,2017
32,North Carolina,NC,False,False,2007.0,0.125,NaN,2021.0,NaN,NaN,NaN,0.013,2017
33,North Dakota,ND,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
34,Ohio,OH,False,False,2008.0,0.125,NaN,2026.0,NaN,NaN,NaN,0.018,2017
35,Oklahoma,OK,True,False,2010.0,0.150,NaN,2015.0,NaN,NaN,NaN,NaN,2017
36,Oregon,OR,False,False,2007.0,0.250,NaN,2025.0,NaN,NaN,NaN,0.04,2017
37,Pennsylvania,PA,False,False,2004.0,0.180,NaN,2020.0,NaN,NaN,NaN,None,2017
38,Rhode Island,RI,False,False,2004.0,0.145,NaN,2019.0,NaN,NaN,NaN,0.12,2017
39,South Carolina,SC,False,False,2014.0,0.020,NaN,2021.0,NaN,NaN,NaN,None,2017
40,South Dakota,SD,True,False,2008.0,0.100,NaN,2018.0,NaN,NaN,NaN,None,2017
41,Tennessee,TN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
42,Texas,TX,False,False,1999.0,NaN,10000.0,2025.0,NaN,NaN,NaN,0.031,2017
43,Utah,UT,True,False,2008.0,0.200,NaN,2025.0,NaN,NaN,NaN,None,2017
44,Vermont,VT,False,False,2015.0,0.550,NaN,2017.0,0.75,2032.0,NaN,None,2017
45,Virginia,VA,True,False,2007.0,0.150,NaN,2025.0,NaN,NaN,NaN,None,2017
46,Washington,WA,False,False,2006.0,0.150,NaN,2020.0,NaN,NaN,NaN,0.04,2017
47,West Virginia,WV,True,True,2009.0,0.100,NaN,2015.0,NaN,NaN,NaN,NaN,2017
48,Wisconsin,WI,False,False,1998.0,0.100,NaN,2015.0,NaN,NaN,NaN,None,2017
49,Wyoming,WY,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
50,Washington DC,DC,False,False,2005.0,0.200,NaN,2020.0,1.00,2032.0,NaN,0.189,2017

In [25]:
for i in range(0, 51):
    curr_value = states.loc[i, "nearest_year"]
    target_year = states.loc[i, "first_target_year"]
    if not isinstance(target_year, float):
        target_year = 0
    print(target_year)
    print(curr_value)
    states.at[i, "nearest_year"] =  curr_value if curr_value < target_year else target_year
    
states

2025.0
0
nan
0

ValueError: Cannot assign nan to integer series

In [21]:
rps_states_set

{'AZ',
 'CA',
 'CO',
 'CT',
 'DC',
 'DE',
 'IA',
 'IL',
 'MA',
 'MD',
 'ME',
 'MI',
 'MN',
 'MO',
 'MT',
 'NC',
 'NH',
 'NJ',
 'NM',
 'NV',
 'NY',
 'OH',
 'OR',
 'PA',
 'RI',
 'TX',
 'VT',
 'WA',
 'WI'}

In [22]:
voluntary_states = {"UT", "ND", "SD", "KS", "OK", "IN", "VA", "SC"}
voluntary_states

{'IN', 'KS', 'ND', 'OK', 'SC', 'SD', 'UT', 'VA'}